<a href="https://colab.research.google.com/github/Sreenidhi-G2/AudioDeepfake/blob/main/NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import nltk
nltk.download("punkt_tab")
from nltk.tokenize import word_tokenize

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


In [ ]:
#program 1 tokenize text

def tokenization(text, method = ""):
  if method == "lines":
    text = text.split('\n')
    return text
  if method == "words":
    text = text.split()
    return text
  if method == "word_tokenize":
    text = word_tokenize(text)
    return text

text = """This is a sample text to perform word tokenizing
 This has multiple lines and lot of characters"""

print(tokenization(text, "lines"))
print(tokenization(text, "words"))
print(tokenization(text, "word_tokenize"))





['This is a sample text to perform word tokenizing ', ' This has multiple lines and lot of characters']
['This', 'is', 'a', 'sample', 'text', 'to', 'perform', 'word', 'tokenizing', 'This', 'has', 'multiple', 'lines', 'and', 'lot', 'of', 'characters']
['This', 'is', 'a', 'sample', 'text', 'to', 'perform', 'word', 'tokenizing', 'This', 'has', 'multiple', 'lines', 'and', 'lot', 'of', 'characters']


In [ ]:
#Lemmetization and Stemming PorterStemmer() .stem

import nltk
nltk.download("punkt")
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer

text = "Write written writting  writes"


words = word_tokenize(text)

stemmer = PorterStemmer()


stem_groups = {}


for word in words:
  stem  = stemmer.stem(word)
  if stem not in stem_groups:
    stem_groups[stem] = []
  stem_groups[stem].append(word)



for form, stem in stem_groups.items():
  print(f"{stem} -> {form}")


['Write', 'writes'] -> write
['written'] -> written
['writting'] -> writ


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [ ]:
#Implement Corpus First 10 words , "The" Count , collocation_list(), FreqDist() , most_common()
import nltk
from nltk.corpus import brown

nltk.download("brown")
nltk.download("stopwords")


words = brown.words()

print("The first 10 first in brown corpus")
print(words[:10])

print("number of words in the Brown Corpus")
print(len(words))


colloc = nltk.Text(words).collocation_list()

print("Collocation list of brown Corpus ", colloc)


word_count = words.count("The")
print("the number of times the word THE is used in corpus")
print(word_count)


print("The Freq_dist of the courpus")
freq_dist = nltk.FreqDist(words)
print(freq_dist.most_common(10))

[nltk_data] Downloading package brown to /root/nltk_data...
[nltk_data]   Package brown is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


The first 10 first in brown corpus
['The', 'Fulton', 'County', 'Grand', 'Jury', 'said', 'Friday', 'an', 'investigation', 'of']
number of words in the Brown Corpus
1161192
Collocation list of brown Corpus  [('United', 'States'), ('New', 'York'), ('per', 'cent'), ('Rhode', 'Island'), ('years', 'ago'), ('Los', 'Angeles'), ('White', 'House'), ('Peace', 'Corps'), ('World', 'War'), ('San', 'Francisco'), ('United', 'Nations'), ('General', 'Motors'), ('fiscal', 'year'), ('could', 'see'), ('New', 'Orleans'), ('Civil', 'War'), ('last', 'year'), ('New', 'England'), ('even', 'though'), ('Air', 'Force')]
the number of times the word THE is used in corpus
7258
The Freq_dist of the courpus
[('the', 62713), (',', 58334), ('.', 49346), ('of', 36080), ('and', 27915), ('to', 25732), ('a', 21881), ('in', 19536), ('that', 10237), ('is', 10011)]


In [ ]:
#Processing text Removing Puntuations and Stop Words

import nltk
from nltk.corpus import stopwords
import string


text = "This is a sample text to remove stop_words and puntutions! "


words = "".join(char for char in text if char not in string.punctuation)

texts = nltk.word_tokenize(words)

stop_words = set(stopwords.words("english"))

filterd = [token for token in texts if token not in stop_words]

print(filterd)

['This', 'sample', 'text', 'remove', 'stopwords', 'puntutions']


In [ ]:
#Chunking

import nltk
nltk.download("punkt")
nltk.download("punkt_tab" )
nltk.download("averaged_perceptron_tagger_eng")

text = "THis is a sample text to perform Chunking on  Text"


words = nltk.word_tokenize(text)

tokens = nltk.pos_tag(words)

print(tokens)

chunking_grammer = r""" NP : {<DT>?<JJ>*<NN> }
VP : {<VB.*><NP|PP>} """


chunk_parser = nltk.RegexpParser(chunking_grammer)
chunk_parse = chunk_parser.parse(tokens)
chunk_parse.pretty_print()

[('THis', 'NNP'), ('is', 'VBZ'), ('a', 'DT'), ('sample', 'JJ'), ('text', 'NN'), ('to', 'TO'), ('perform', 'VB'), ('Chunking', 'VBG'), ('on', 'IN'), ('Text', 'NNP')]
                                         S                                             
    _____________________________________|_________________________                     
   |       |       |           |         |      |                  VP                  
   |       |       |           |         |      |        __________|______              
   |       |       |           |         |      |       |                 NP           
   |       |       |           |         |      |       |      ___________|________     
THis/NNP to/TO perform/VB Chunking/VBG on/IN Text/NNP is/VBZ a/DT     sample/JJ text/NN



[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!


In [ ]:
#Chinking

import nltk
nltk.download("punkt")
nltk.download("punkt_tab" )
nltk.download("averaged_perceptron_tagger_eng")

text = "THis is a sample text to perform Chunking on  Text"


words = nltk.word_tokenize(text)

tokens = nltk.pos_tag(words)

print(tokens)

chunking_grammer = r""" NP : {<.*>+}
}<VB.*|IN>+{  """


chunk_parser = nltk.RegexpParser(chunking_grammer)
chunk_parse = chunk_parser.parse(tokens)
chunk_parse.pretty_print()

[('THis', 'NNP'), ('is', 'VBZ'), ('a', 'DT'), ('sample', 'JJ'), ('text', 'NN'), ('to', 'TO'), ('perform', 'VB'), ('Chunking', 'VBG'), ('on', 'IN'), ('Text', 'NNP')]
                                        S                                          
   _____________________________________|_____________________________________      
  |        |           |         |      NP             NP                     NP   
  |        |           |         |      |       _______|_______________       |     
is/VBZ perform/VB Chunking/VBG on/IN THis/NNP a/DT sample/JJ text/NN to/TO Text/NNP



[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!


In [ ]:
#Webscraping

import requests
from bs4 import BeautifulSoup
url = "https://www.google.co.in/"


response = requests.get(url)

soup = BeautifulSoup(response.content , "html.parser")

text = soup.get_text()

tokens = nltk.word_tokenize(text)

tags = nltk.pos_tag(tokens)
print(tags)

[('GoogleGmailImagesSign', 'NNP'), ('in', 'IN'), ('Advanced', 'NNP'), ('searchAdvertisingBusiness', 'NN'), ('SolutionsAbout', 'NNP'), ('Google©', 'NNP'), ('2026', 'CD'), ('-', ':'), ('Privacy', 'NN'), ('-', ':'), ('TermsGoogle', 'NN'), ('apps', 'NN')]


In [ ]:
#sentiment Program
from textblob import TextBlob

text = "This movie is really good and interesting"



analysis = TextBlob(text)

if analysis.sentiment.polarity > 0:
  print("positive")
if analysis.sentiment.polarity < 0:
  print("negative")


print(analysis.subjectivity)
print(analysis.polarity)
print(text)




positive
0.55
0.6
This movie is really good and interesting


In [ ]:
#ngrams

import nltk
from nltk.util import ngrams


text = "I love NLP subject because it is very helpful"



words = nltk.word_tokenize(text)


n = 3


grams = list(ngrams(words, n))


for gram in grams:
  print(gram)

('I', 'love', 'NLP')
('love', 'NLP', 'subject')
('NLP', 'subject', 'because')
('subject', 'because', 'it')
('because', 'it', 'is')
('it', 'is', 'very')
('is', 'very', 'helpful')


In [ ]:
# Smothing
import nltk

def laplace_smothing(words , vocab_size):
  smoothing = {}
  total_count = sum(words.values())
  for w , c in words.items():
    smoothing[w] = (c + 1) / (total_count + vocab_size)
  return smoothing



words = {"apple" : 3 , "banana" : 2 , "Oranage" : 2}
vocab_size = 100;

smooth = laplace_smothing(words , vocab_size)
for w , c in smooth.items():
  print(w  ,"=", c)


apple = 0.037383177570093455
banana = 0.028037383177570093
Oranage = 0.028037383177570093


In [ ]:
#News Program

from sklearn.datasets import fetch_20newsgroups
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression


data = fetch_20newsgroups(subset  = "all")


X_train , X_test , y_train , y_test = train_test_split(data.data, data.target, test_size = 0.3,random_state= 42 )


model = make_pipeline(TfidfVectorizer(stop_words = "english") , LogisticRegression(max_iter = 1000))

model.fit(X_train , y_train)



accuracy = model.score(X_test, y_test)
print(accuracy)

text = "NASA is worst"

idx = model.predict([text])[0]

print("Prediction  = ", data.target_names[idx])






0.9013088079235939
Prediction  =  sci.space


In [6]:
#information Extraction

import email

from email.policy import default



email_content = """From: sreenidhig2005@gmail.com
To: sree@gmail.com
Subject: Sample Mail
This mail is to demonstrate inforamtion extraction
"""


msg = email.message_from_string(email_content, policy = default)
body = msg.get_content().strip()


print("Body=" , body)
To = msg['To']
fro = msg['From']

print(To)
print(fro)

Body= This mail is to demonstrate inforamtion extraction
sree@gmail.com
sreenidhig2005@gmail.com


In [9]:
import nltk
nltk.download("averaged_perceptron_tagger_eng")
nltk.download("punkt_tab")

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger_eng.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [12]:
#Meaning Representation

text = " the dog is running like a horse"

words = nltk.word_tokenize(text)


tags = nltk.pos_tag(words)


nouns = [w for w , t in tags if t.startswith("NN")]
adjs = [w for w , t in tags if t.startswith("JJ")]
verbs = [w for w , t in tags if t.startswith("VB")]

if(nouns):
  print("Nouns = " , nouns)

if adjs:
  print("Adjective = " , adjs)


if verbs :
  print("Verbs = ", verbs)

Nouns =  ['dog', 'horse']
Verbs =  ['is', 'running']


In [18]:
#Disambiguity


import nltk

nltk.download("wordnet")

from nltk.corpus import wordnet as wn

def lexalgo(sentence , word):
  words = set(nltk.word_tokenize(sentence))
  synsets = wn.synsets(word)


  if not synsets:
    return None

  def getoverlap(sense):
    return len(words & set(nltk.word_tokenize(sense.definition())))


  return max(synsets,key = getoverlap)












[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [19]:
result = lexalgo("THe dog is sitting near the bank", "bank")
print(result.definition())


a slope in the turn of a road or track; the outside is higher than the inside in order to reduce the effects of centrifugal force


In [22]:
#Question answer system


from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity


corpus = [
    "newton invented laws of motion ",
    "AryaBhata invented Zero " ,
    "ISRO was started BY APJ Abdul Kalam"
]


questions = ["who started ISRO","who invented Zero" ]


vec = TfidfVectorizer(stop_words = "english")

X = vec.fit_transform(corpus)


for q in questions:
  q_vec= vec.transform([q])
  idx = cosine_similarity(q_vec , X).argmax()
  print("Q = ",q)
  print("A = ",corpus[idx])






Q =  who started ISRO
A =  ISRO was started BY APJ Abdul Kalam
Q =  who invented Zero
A =  AryaBhata invented Zero 


In [23]:
#masking


import numpy as np


size =10
i, j = np.indices([size , size ])


mask = (i >= j).astype(int)


print(mask)


print(mask.T)

[[1 0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0]
 [1 1 1 0 0 0 0 0 0 0]
 [1 1 1 1 0 0 0 0 0 0]
 [1 1 1 1 1 0 0 0 0 0]
 [1 1 1 1 1 1 0 0 0 0]
 [1 1 1 1 1 1 1 0 0 0]
 [1 1 1 1 1 1 1 1 0 0]
 [1 1 1 1 1 1 1 1 1 0]
 [1 1 1 1 1 1 1 1 1 1]]
[[1 1 1 1 1 1 1 1 1 1]
 [0 1 1 1 1 1 1 1 1 1]
 [0 0 1 1 1 1 1 1 1 1]
 [0 0 0 1 1 1 1 1 1 1]
 [0 0 0 0 1 1 1 1 1 1]
 [0 0 0 0 0 1 1 1 1 1]
 [0 0 0 0 0 0 1 1 1 1]
 [0 0 0 0 0 0 0 1 1 1]
 [0 0 0 0 0 0 0 0 1 1]
 [0 0 0 0 0 0 0 0 0 1]]


In [29]:
#positional Encoding


import numpy as np

def getpe(dim , seq_len):
 pos = np.arange(seq_len)[:,None]

 div = 10000**(np.arange(0,dim,2)/dim)

 pe = np.zeros((seq_len , dim))

 pe[:,0::2] = np.sin(pos/div)
 pe[:,1::2] = np.cos(pos/div)
 return pe






pe = getpe(512,10)
print(pe[:2,:4])



[[0.         1.         0.         1.        ]
 [0.84147098 0.54030231 0.82185619 0.56969501]]


In [30]:
from collections import Counter

In [33]:
#program Good Turing

def getgood(counts):
  freq_counts = Counter(counts.values())
  total = sum(counts.values())

  good_grps = {}
  for word , count in counts.items():
    nk = freq_counts[count]
    nk1 = freq_counts.get(count +1 , 0)

    if nk1 > 0:
      adjusted = (count + 1) * (nk1 / nk)
    else:
      adjusted = count


    good_grps[word] = adjusted / total

  return good_grps













ngram_counts = {
    'the': 5,
    'of': 3,
    'and': 3,
    'to': 2,
    'a': 2,
    'in': 1
}


res = getgood(ngram_counts)
print(res)





{'the': 0.3125, 'of': 0.1875, 'and': 0.1875, 'to': 0.1875, 'a': 0.1875, 'in': 0.25}
